language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: R9yItpWpJIIyXN3i6YV9xoC1fox1MhJDftj8j9JWlOKRzfB/+DagpOH2PIPEmhlDTgeWsrx4NnMOpxvSWXyDly2yGzD5JTnXwpnFgV+2//betn/bet7UejhakhkRCGQjKnl8rf0xsVsn1igzBanGPx26Ep9SaYWPsw5liLyyA/U=
  on:
    tags: true
    repo: valet-io/directives
